apiVersion: v2
version: 0.3.0

name: zimagi
type: application
description: A Helm chart for deploying the Zimagi data management platform.

dependencies:
- name: zimagi-lib
  repository: https://charts.zimagi.com
  version: 0.x.x

maintainers:
- email: erik.jagyugya@dccs.tech
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: adrian.webb@dccs.tech
  name: adrianwebb
  url: https://github.com/adrianwebb
