
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certIssuer.name }}
spec:
  acme:
    email: {{ .Values.certIssuer.email }}
    server: {{ .Values.certIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.certIssuer.secretName }}
    solvers:
    {{- if .Values.certIssuer.httpResolver.enabled }}
    - http01:
        ingress:
          class: {{ .Values.certIssuer.httpResolver.ingressClass }}
    {{- end }}
    {{- if .Values.certIssuer.cloudflareResolver.enabled }}
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: {{ .Values.certIssuer.cloudflareResolver.apiTokenSecretName }}
            key: {{ .Values.certIssuer.cloudflareResolver.apiTokenSecretKey }}
    {{- end }}